### ISSUE TITLE
Publishing to chocolately automatically using TeamCity

### ISSUE THREAD

**Issue by shiftkey** [Code52/pretzel#119]
TODO:

 - [x] wireup configuration on TeamCity to build on new changes
 - [x] fix the failing test which is due to whitespace and probably jgit doing LF instead of CRLF
 - [x] proper versions and linking to git hash in local scripts and TeamCity builds
 - [x] get chocolatey packages being created as well as zip packages
 - [x] get version flowing from TeamCity into packages (with dev build having a placeholder version)
 - [x] ping @JakeGinnivan to get details of chocolatey creds
 - [ ] do we want a pre-release and stable packages?

**Comment by laedit** [comment]
Done with AppVeyor as continuous integration.
