### ISSUE TITLE
Sporadically crashes on "Taste" caused by 'Cannot access a disposed object.'

### ISSUE THREAD

**Issue by jhovgaard** [Code52/pretzel#147]
I haven't been able to figure out what causes this to happen. I can easly be recreated by simply sending about 100 requests in short a time (keep pressing F5 ;-)) I've attached the full stacktrace. When restarting "taste" everything works again.

#### Stacktrace
![mnrg2zmfxm_733couknlzfufmfpd43a66lyqfq-2c3g](https://f.cloud.github.com/assets/1388347/709698/416611c6-de6d-11e2-9e6e-584ee55adda8.png)

**Comment by markvantilburg** [comment]
This still happens in the current version. I tried with the debugger attached but visual studio was not able to show what object it tries to access.

**Comment by markvantilburg** [comment]
Call stack according to intellitrace 

>	Pretzel.exe!Firefly.Utils.SocketWrapper.Shutdown(System.Net.Sockets.SocketShutdown how = {unknown})	C#
 	Pretzel.exe!<>c__DisplayClass9.AnonymousMethod()	C#
 	Pretzel.exe!<>c__DisplayClass6.AnonymousMethod()	C#
 	Pretzel.exe!Firefly.Utils.SocketSender.SetStateImmediate()	C#
 	Pretzel.exe!Firefly.Utils.SocketSender.DoSendCompleted()	C#
 	Pretzel.exe!Firefly.Utils.SocketSender.SocketEventCompleted()	C#
 	Pretzel.exe!Firefly.Utils.SocketEventWrapper.SocketEventCompleted(object sender = {unknown}, System.Net.Sockets.SocketAsyncEventArgs e = {unknown})	C#

**Comment by laedit** [comment]
This is coming from the embedded server which is no longer supported...
We need to replace it but I haven't found any equivalent.

**Comment by markvantilburg** [comment]
Would it be easy to replace the server with IIS Express (if the user has that installed?)

**Comment by markvantilburg** [comment]
It cannot be embedded currently but we could suggest the user to install it, and use it if it's installed. 

And for example use a command line parameter to enable the use of iisexpress where taste creates an on disk folder and points iis express to there.

**Comment by laedit** [comment]
I don't think having a dependency on a thing as heavy and complex as IIS Express is a good thing.
Specially since the issue here is not blocking.
I think it should be best to replace Firefly with maybe [NHttp](https://github.com/pvginkel/NHttp) or juste [HttpListener](https://msdn.microsoft.com/en-us/library/system.net.httplistener.aspx).

**Comment by JakeGinnivan** [comment]
https://www.nuget.org/packages/Nancy.Hosting.Self is another option suggested by twitter

**Comment by laedit** [comment]
I don't think we need the specificity of Nancy Hosting, we can just use [Microsoft.Owin.Host.HttpListener](http://www.nuget.org/packages/Microsoft.Owin.Host.HttpListener/].

**Comment by SimonCropp** [comment]
i have lots of love for nancy. perhaps a little too large for this usage, although perhaps that is insignificant compared to getting something stable and well supported in

**Comment by damianh** [comment]
:-1: for depending on IIS.

Firefly http server is well dead. NHttp doesn't support owin and looks old too.

Use Microsoft.Owin.Host.HttpListener or [Nowin](https://github.com/Bobris/Nowin). [Example](https://github.com/Sandra/Sandra.Snow/blob/master/src/Snow/SnowServer.cs)

**Comment by pysco68** [comment]
Just saw the tweet for this issue. I'll recommend Nowin. We use it in five bigger scale intranet applications. The greatest point is support for web sockets on any platform. Plus its really fast (10000 concurrent requests per second are doable as long as the business logic is fast - on a single process)

**Comment by damianh** [comment]
Also, since Nowin doesn't depend on Http.sys, you don't have to fup around with Http ACLs

**Comment by laedit** [comment]
Thanks for the advices, I think we'll go with Nowin.
@markvantilburg I don't have the time to work on this right now, but a PR is welcome :smiley:

**Comment by markvantilburg** [comment]
Cannot get it to crash anymore after the change of #298

**Comment by markvantilburg** [comment]
Maybe #102 can also be closed with the fix of #298

**Comment by laedit** [comment]
Thanks for the update.
