### ISSUE TITLE
Chocolatey Package Feedback

### ISSUE THREAD

**Issue by shiftkey** [Code52/pretzel#196]
Thanks @ferventcoder for raising these two questions about the [latest release](https://chocolatey.org/packages/pretzel/0.2.0.42):

 - What is the license on this?
 - Can you shift over to get-binroot?

I'll see if I can put together a PR to address this, unless @laedit or @JakeGinnivan beats me to the punch...

**Comment by ferventcoder** [comment]
If the release adds security changes or something else super important, I can let this one through approval while you work out the fixes. Let me know.

**Comment by laedit** [comment]
I've added the licenseUrl in the nuspec, but for the folder I used what I see in [Install-ChocolateyZipPackage](https://github.com/chocolatey/chocolatey/wiki/HelpersInstallChocolateyZipPackage).
So the unzipLocation must use Get-BinRoot?

**Comment by laedit** [comment]
@fervent by the way, sorry about the double push, I didn't know it is possible to push the same package version.
The only difference between 0.2.0.41 and 0.2.0.42 is that the zip url of 0.2.0.41 is bad.

**Comment by ferventcoder** [comment]
We like to see it use Get-BinRoot instead of c:\tools. It's a six to one half dozen to the other as we are about to deprecate the usage of it (and pushing things to c:\tools in the first place with new choco - which doesn't put versions on folders).

**Comment by laedit** [comment]
I understand totally, is is preciselly one of the thing fixed by the new ChocolateyInstall.ps1 of the 0.2.0.* releases: the uninstallation of the old C:\tools\pretzel folder and PATH.
The installation now use `"$(Split-Path -parent $MyInvocation.MyCommand.Definition)"`.
Is it the right thing to do?
Do we need to drop the uninstallation of the old pretzel folder/PATH?

**Comment by ferventcoder** [comment]
It couldn't hurt to help with transition.

**Comment by laedit** [comment]
Ok, but there is still a possible conflict on the PATH env variable with the chocolatey path containing the shim to pretzel.exe and the old folder (c:\tools\preztel).
But maybe is it cleaner to do this in an UninstalChocolatey.ps1 script?

**Comment by ferventcoder** [comment]
Yes there would still be potential for that. Removing the path item and the
old path would be good. Perhaps add those to the current pkg and change the
install script for next release?

On Wednesday, January 28, 2015, Jérémie Bertrand <notifications@github.com>
wrote:

> Ok, but there is still a possible conflict on the PATH env variable with
> the chocolatey path containing the shim to pretzel.exe and the old folder
> (c:\tools\preztel).
> But maybe is it cleaner to do this in an UninstalChocolatey.ps1 script?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Code52/pretzel/issues/196#issuecomment-71809880>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by laedit** [comment]
So if I understand well for the 0.2.0.42 I just add the licenseUrl and for the next release we need to delete all the old PATH/Folder part.
A big thanks for your help and sorry to have bothered you the all day.

**Comment by ferventcoder** [comment]
License url plus chocolateyUninstall.ps1 to remove it. Then next release you can add the transition bits.

Then folks can install the new version, transition off of the older one with `choco uninstall pretzel --version 0.2.0.42`

**Comment by laedit** [comment]
Ok I have pushed another version of 0.2.0.42 with `licenseUrl` and `chocolateyUninstal.ps1`.
Thanks again @ferventcoder for your help!

**Comment by laedit** [comment]
@ferventcoder sorry to bother you but I haven't any news of the state of the new package, is it ok?
Or do I need to do some modification?
Thanks.

**Comment by ferventcoder** [comment]
Good to go. Sorry for the wait.

**Comment by laedit** [comment]
No problem, I was thinking I had done something wrong.
Thanks again for your help!
