### ISSUE TITLE
PostUrl in Razor

### ISSUE THREAD

**Issue by AndreyAkinshin** [Code52/pretzel#209]
In Luquid, I can write `{% post_url my-post-name %}` and get a link of the post. How I can do the same on Razor?

**Comment by laedit** [comment]
Sadly PostUrl isn't available on Razor side for now.

@shiftkey, @JakeGinnivan I propose to do with Tag that is already done for IFilter: add an ITag interface which will be used by engines and registered as Liquid Tag for LiquidEngine and with ExtensibleTemplate for Razor, which for example for PostUrl we will have:
Liquid:
```
{% post_url my-post-name %}
```
And for Razor:
```
@Filter.PostUrl("my-post-name")
```

**Comment by JakeGinnivan** [comment]
Don't have an opinion on this, go nuts :)

**Comment by laedit** [comment]
PostUrl tag is now usable in Razor:
```
@Tag.PostUrl("my-post-name")
```
