### ISSUE TITLE
Url processing

### ISSUE THREAD

**Issue by AndreyAkinshin** [Code52/pretzel#210]
I want to convert all my urls to downcase and replace special charachters with equivalents (for example `.` -> `dot`). For example, I want to replace the `.NET` category name to `dotnet` in url. Also it would be great do remove `index.html` from url. For example, `/blog/.NET/postname/index.html` -> `/blog/dotnet/postname/`.

How I can do it?

**Comment by AndreyAkinshin** [comment]
Any ideas?

**Comment by laedit** [comment]
The `slugify` and `prettify` filters can help you do that.

**Comment by laedit** [comment]
I forgot to add the syntax:
Liquid:
```
{{ 'http://mysite.com/index.html' | prettify_url}}
{{ '.NET C#' | slugify}}
```

Razor:
```
@Filter.PrettifyUrl(\"http://mysite.com/index.html\")
@Filter.Slugify(\".ASP.NET MVC\")
```
