### ISSUE TITLE
Tables and Github Flavoured Markdown in general

### ISSUE THREAD

**Issue by elacy** [Code52/pretzel#237]
Best case I'd like to be able to use Github Flavoured Markdown and have it just work.

Next best case I'd like to at least be able to use tables.

Any idea what the best way of adding support for that in is?

**Comment by laedit** [comment]
Sadly it won't be easy.

We use [CommonMark.NET](https://github.com/Knagis/CommonMark.NET) for markdown conversion, which is a .net implementation of [CommonMark](http://commonmark.org/). There are members of GitHub involved in the project but not all GitHub Flavoured Markdown is supported right now, it's still young in the markdown world. The tables are not supported but are in discussion.

A possible solution could be to create a plugin which add custom `IContentTransform`, which could use another markdown converter (like MarkdownDeep) to convert the content of a particular block. You could use [WebSequenceDiagrams](https://github.com/Code52/pretzel/blob/master/src/Pretzel.Logic/Extensibility/Extensions/WebSequenceDiagrams.cs) as example.
Right now the extensibility is not documented, but all you have to do is create a dll which reference Pretzel and create a class which implement `IContentTransform` and put the resulting dll fil to a `_plugins` folder in your site folder.
And I am working on a [PR](https://github.com/Code52/pretzel/pull/229) which will allow to create plugin from [ScriptCs](https://github.com/scriptcs/scriptcs) scripts.

**Comment by EvaKnievel** [comment]
Thanks so much for your reply,

I'm kind of worried about what MarkdownDeep might do to the HTML if there is some sort of bad html removing that goes on?

It would be awesome if I could swap out CommonMark.Net for another markdown converter

It would also be handy if there pre processing transformers as well as post processing if that makes sense.

**Comment by laedit** [comment]
I don't think that MardownDeep will interpret any HTML code, but I can't verify it.

The markdown conversion is sadly hard-coded but it's possible to make it extensible in order to replace it by another markdown interpreter.

We have only post processing but as already said, we are open to discussion and PR :smiley:

**Comment by laedit** [comment]
The current dev version of Pretzel has now an extension point for the Markdown engine and I have made a [plugin for MarkdownDeep](https://github.com/laedit/Pretzel.MarkdownDeep).
