### ISSUE TITLE
Error when baking brand new razor template site

### ISSUE THREAD

**Issue by WalkerCodeRanger** [Code52/pretzel#240]
Just installed pretzel 0.2.0.42 from [chocolatey](https://chocolatey.org/packages/pretzel) and went to make a new razor site and got an error

	C:\site>pretzel create -t=razor
	starting pretzel...
	create - configure a new site
	Using razor Engine
	Pretzel site template has been created

	C:\site>pretzel bake
	starting pretzel...
	bake - transforming content into a website
	Recommended engine for directory: 'razor'
	Failed to render template, falling back to direct content
	done - took 5808ms

	C:\site>

Not sure which template it is actually failing on as most of the site seems to have been generated.

**Comment by johnboker** [comment]
It looks like in `SiteConextGenerator.cs` there is this code:

    html = Path.GetExtension(file).IsMarkdownFile()				   
        ? CommonMark.CommonMarkConverter.Convert(contentsWithoutHeader).Trim()
        : contentsWithoutHeader; 

the html generated by `CommonMark.CommonMarkConvert.Convert` is not valid for a razor template.  It contains html entities like &amp;gt; that cause the razor engine to fail.

**Comment by laedit** [comment]
Thanks for the feedbak.
Normally this is fixed with the current master branch, can you try it?
You can find the latest binaries on [AppVeyor](https://ci.appveyor.com/project/laedit/pretzel/build/artifacts).

**Comment by WalkerCodeRanger** [comment]
Works when built from master branch (5df3cfaae513888edef4d205f5e1857731c92551).  You guys should either release a new version or at least update the docs to reflect that 0.2.0.42 isn't a good version.  I was already moving to the master branch because I found it fixed issue #199 which is a pretty big deal too if you ask me.

**Comment by laedit** [comment]
I plan to release the v0.3 soon but before I want to fix some recent feedback like yours.
