### ISSUE TITLE
Should support --version switch

### ISSUE THREAD

**Issue by WalkerCodeRanger** [Code52/pretzel#241]
I went to report my issue and wanted to make sure I specified which version of pretzel I was running.  I expected that like most tools it would have a way to get the the version, but it doesn't.  Ideally, both `pretzel --version` and `pretzel -v` would be supported.

**Comment by shiftkey** [comment]
:thumbsup:

**Comment by laedit** [comment]
I have added a `pretzel version` command which only display the version, and the `-debug` now always display the version.
