### ISSUE TITLE
Update nuget packages

### ISSUE THREAD

**Issue by markvantilburg** [Code52/pretzel#251]
I tried and updated all nuget packages in the project locally to their latest stable versions - that does not result in broken tests.

But xunit.net needs to be updated manually.

@laedit maybe you can update the packages used in the master-branch?

**Comment by markvantilburg** [comment]
I think this issue #121 can be closed.

**Comment by laedit** [comment]
That's a good idea but can't do it right now.
I'll work on it when I return home in about 4 weeks.
