### ISSUE TITLE
Add support for Liquid {% break %}

### ISSUE THREAD

**Issue by 2moveit** [Code52/pretzel#252]
The current Liquid version supports break and continue: https://github.com/Shopify/liquid/pull/140
Pretzel should support it, too.

Exception: Pretzel.Logic.Exceptions.PageProcessingException: Failed to proc
ess ...\_site\index.html, see inner e
xception for more details ---> DotLiquid.Exceptions.SyntaxException: Unknown tag
 'break'
   bei DotLiquid.Block.UnknownTag(String tag, String markup, List`1 tokens)
   bei DotLiquid.Tags.If.UnknownTag(String tag, String markup, List`1 tokens)
   bei DotLiquid.Block.Parse(List`1 tokens)
   bei DotLiquid.Tags.If.Initialize(String tagName, String markup, List`1 tokens
)
   bei DotLiquid.Block.Parse(List`1 tokens)
   bei DotLiquid.Tags.For.Initialize(String tagName, String markup, List`1 token
s)
   bei DotLiquid.Block.Parse(List`1 tokens)
   bei DotLiquid.Document.Initialize(String tagName, String markup, List`1 token
s)
   bei DotLiquid.Template.ParseInternal(String source)
   bei Pretzel.Logic.Templating.Jekyll.LiquidEngine.RenderTemplate(String templa
teContents, PageContext pageData)
   bei Pretzel.Logic.Templating.JekyllEngineBase.ProcessFile(String outputDirect
ory, Page page, Page previous, Page next, Boolean skipFileOnError, String relati
vePath)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Pretzel.Logic.Templating.JekyllEngineBase.ProcessFile(String outputDirect
ory, Page page, Page previous, Page next, Boolean skipFileOnError, String relati
vePath)
   bei Pretzel.Logic.Templating.JekyllEngineBase.Process(SiteContext siteContext
, Boolean skipFileOnError)
   bei Pretzel.Commands.BakeCommand.Execute(IEnumerable`1 arguments)
   bei Pretzel.Program.Run(String[] args, OptionSet defaultSet)
   bei Pretzel.Program.Main(String[] args)

**Comment by markvantilburg** [comment]
Dotliquid supports it, but the nuget package https://www.nuget.org/packages/DotLiquid/ is not updated yet.

https://github.com/dotliquid/dotliquid/commit/b073782421b196668b137a496dd1228cab9200fe

**Comment by markvantilburg** [comment]
@laedit can you pull a new dotliquid build inside?

**Comment by laedit** [comment]
They haven't released a new version so I don't know what I can do.

**Comment by markvantilburg** [comment]
My mistake, it's not the custom build version from the libs folder that is used.
https://github.com/Code52/pretzel/tree/master/libs

**Comment by laedit** [comment]
Thanks for pointing that out, this folder must be deleted.

**Comment by markvantilburg** [comment]
@laedit since there is a custom build included that has this feature. This can be closed.

**Comment by laedit** [comment]
@markvantilburg thanks.
