### ISSUE TITLE
Unhandled exception during import of (admitedly large) wordpress XML export file

### ISSUE THREAD

**Issue by jrjones** [Code52/pretzel#256]
When importing a large wordpress XML file, I received a null reference exception (quoted below.) When I get a chance in the next few days I will try to get it running in a debugger, but it's completely reproducible. 

```
C:\pretzel>pretzel import --i=wordpress --f=./jrjblog.xml --s=./_site
starting pretzel...
import - import posts from external source
 
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
 at Pretzel.Logic.Import.WordpressImport.<>c__DisplayClass6.<Import>b__1(XElement e)
 at System.Linq.Enumerable.WhereSelectEnumerableIterator 2.MoveNext()
 at Pretzel.Logic.Import.WordpressImport.Import()
 at Pretzel.Commands.ImportCommand.Execute(IEnumerable 1 arguments)
 at Pretzel.Program.Run(String[] args, OptionSet defaultSet)
 at Pretzel.Program.Main(String[] args)
```

**Comment by jrjones** [comment]
Ugh... really? I can't upload the XML file for the repro? Lame, GitHub. 

If you want to repro, you can [download the XML file from my S3 bucket](http://www.jrj.io/jrjblog-export.xml).

**Comment by thiagoabreu** [comment]
The namespaces' versions were hard coded to wp 1.1. Your xml have an attribute "xmlns:wp" at root  with version "1.2". Should work now.

**Comment by jrjones** [comment]
That did it, I was able to build and confirm that the fix resolves the issue. Thanks for the ridiculously quick turnaround!
