### ISSUE TITLE
Taste trigers complete site regeneration for excluded items

### ISSUE THREAD

**Issue by kodfodrasz** [Code52/pretzel#264]
While using VisualStudio Code to write posts and layouts in a git version controlled site source I have noticed that while tasting the site was continously being regenerated for changes in the .git folder.
I have added the folder and git items to the config as follows:
~~~yaml
exclude:
  - .gitignore
  - .git
  - taste.bat
  - Pretzel.exe
~~~
Now the excluded items did not get copied, but were still triggering the regeneration.

**Comment by laedit** [comment]
I'm good with the issue, since Jekyll seems to do the same.
Just for my sake, I haven't got the time to test it, normally all hidden folder are excluded by default, it isn't the case?
And I'm wondering if all git/pretzel files (.git, .gitignore, .gitattributes, pretzel.exe, etc...) should be excluded by default.
What do you think?

**Comment by kodfodrasz** [comment]
I'm also not sure if those should be excluded. Actually the .entries are not "hidden" on windows.

On the other hand if Jekyll automatically skips them then it would be reasonable to stay compatible with Jekyll, but I don't know Jekyll's behavior. I'll test it sometime this week and update the issue, and the PR accordingly.

**Comment by laedit** [comment]
Thanks, you are awesome! :smiley:

**Comment by markvantilburg** [comment]
For the wiki page, how should this be added?

https://github.com/Code52/pretzel/wiki/Configuration

Exclude items from automatic regenerating the site when using the taste command
```
exclude:
  - .gitignore
  - .git
  - taste.bat
  - Pretzel.exe
```
Where the excluded file is part of the path of a file. So `- example` would not include any file that contains `example` in the file or folder name.

**Comment by laedit** [comment]
Not exactly, at first the exclude configuration is used to exclude files / folders from the generating process. The exclusion of the taste is just a "side effect".

**Comment by markvantilburg** [comment]
Ok updated the description and added it to the configuration wiki.
