### ISSUE TITLE
Exclude needs very specific paths

### ISSUE THREAD

**Issue by markvantilburg** [Code52/pretzel#267]
Currently the exclude needs very specific filenames + path's to exclude files

https://github.com/Code52/pretzel/blob/master/src/Pretzel.Logic/Templating/Context/SiteContextGenerator.cs#L191

If changed to this it becomes easier to exclude files or folders.

```
        private bool IsExcludedPath(string relativePath)
        {
            foreach (string x in excludes)
            {
                if (relativePath.Contains(x))
                {
                    return true;
                }
            }

            return false;
        }
```

The exclude list could look like this
```
exclude:
  - bootstrap\
  - style-green.css
  - animate.css
  - font-awesome.css
```

in the current structure you would need to match the entire path. But maybe that's how it's supposed to be (and should not be changed).

**Comment by laedit** [comment]
We are based on the [Jekyll functionality](http://jekyllrb.com/docs/configuration/):
> Exclude directories and/or files from the conversion. 
> These exclusions are relative to the site's source directory and cannot be outside the source directory.

I prefer that we stay close to Jekyll and in this case the file path is not generally long.
In general your sample will be something like:

    exclude:
      - bootstrap\
      - css\style-green.css
      - css\animate.css
      - css\font-awesome.css

So if it's really a burden we can think to something but for me the `Contains` can lead to unwanted behavior.

**Comment by markvantilburg** [comment]
Wildcards are currently not supported, with the new way you could put ```.cmd``` to ignore all ```.cmd``` files. But wildcards in the middle like ```build*.cmd``` would not be supported.

**Comment by laedit** [comment]
The wildcard support is safer than the `Contains` in my opinion, so if you want to make a PR I will gladly accept it. :smiley:
