### ISSUE TITLE
Update ilmerge since current one needs .NET 3.5 installed 

### ISSUE THREAD

**Issue by nayanshah** [Code52/pretzel#268]
Building the sln fails on a machine without .NET 3.5 installed. Updating ilmerge to latest version 2.14.1208 resolves the issue. 

I think it would be better to consume it from a nuget package instead of checking it into source - https://www.nuget.org/packages/ilmerge/

I can quickly create a PR if there are no concerns with this.

**Comment by laedit** [comment]
See #266, ILMerge will be removed soon.
So thanks but the PR isn't needed.
