### ISSUE TITLE
Liquid tags not rendered on main page when post has no excerpt

### ISSUE THREAD

**Issue by k94ll13nn3** [Code52/pretzel#272]
When a liquid tag is used in a post (like with plugins), it is not rendered on the home page, whether it is a base liquid tag (like {% if %}) or a plugin tag, but it is correctly rendered when viewing the post.

It can be easily reproduced by adding a simple `{% if page.title %}{{page.title}}{% endif %}` on the `myfirstpost.md` page in the test site.

However, when using the excerpt feature, the liquid tags are correctly rendered on the main page, even when the excerpt is equal to the content (when adding the excerpt separator at the end of the post).

So, on the home page, liquid tags are not rendered when using `post.content` but are rendered when using `post.exceprt`.

I will try to take a look at the code if I have time.

I am using the latest version (7a87a57).

**Comment by laedit** [comment]
I think this is the same bug as in #246.
I'll try to fix it during the following week.

**Comment by k94ll13nn3** [comment]
Oh my bad, I searched if there already was an issue, didn't find it. I close this one since it is a duplicate.
