### ISSUE TITLE
IFileSystem in ScriptCs plugins

### ISSUE THREAD

**Issue by thoemmi** [Code52/pretzel#275]
Hi,

I want to convert my plugins ([Pretzel.Sitemap](https://github.com/thoemmi/Pretzel.Sitemap) and [Pretzel.RedirectFrom](https://github.com/thoemmi/Pretzel.RedirectFrom)) from assemblies to ScriptCs. However, currently I let the container inject `IFileSystem` into my classes, but that does not seem to be possible with ScriptCs (I added `IFileSystem` to the types passed to `ScriptCsCatalogFactory.CreateScriptCsCatalog` in [`Program.AddScriptCs`](https://github.com/Code52/pretzel/blob/ead84afc2d961ccd87de5f302defcbf234b0b128/src/Pretzel/Program.cs#L141-L143) but it didn't help)

My suggestion is to either
* pass `IFileSystem` as an additional parameter to `ITransform.Transform`, or
* add a `IFileSystem` property to `SiteContext` (`SiteContextGenerator` could pass it to `SiteContext`)

If you agree on either I'd prepare a pull request.

**Comment by laedit** [comment]
Strange, all ScriptCs plugins must be loaded by MEF, like the other plugins, so the constructor is supposed to have his parameters filled.

What error do you have, only a `NullReferenceException`?

**Comment by thoemmi** [comment]
I have a repro at home, I'll post the exact issue later.

**Comment by thoemmi** [comment]
@laedit The `NullReferenceException` I get is not related to the use of `IFileSystem`. I close this issue, prepare a PR for using `IFileSystem` in ScriptCS, and open another issue for the exception.
