### ISSUE TITLE
Syntax Highlighting does not work

### ISSUE THREAD

**Issue by gburghardt** [Code52/pretzel#276]
I just installed Pretzel 0.2.0.42 and using the triple backtick style of inserting code blocks does not render syntax highlighted code.

Markdown:

    ``` js
    var message = "abc";
    ```

Expected output:

    <pre><code class="js">var message = "abc";</code></pre>

Actual output:

    <p><code>var message = "abc";</code></p>

The wiki page titled [Syntax Highlighting](https://github.com/Code52/pretzel/wiki/Syntax-Highlighting) makes it seem like syntax highlighting is supported "right out of the box" (without any special configurations or fiddling).

This is the command I used to create my new site:

    pretzel create

And even using the "wiki" template:

    pretzel create --wiki --template=razor

With both kinds of sites, the Markdown input generates the same HTML output.

**Comment by JuergenGutsch** [comment]
I have the same problem using the same version.
The indented block is working but without the possibility to add a language to highlight.

**Comment by thoemmi** [comment]
Do you include `highlight.js` in your html?

```
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

It's not explicitly stated on the wiki page [Syntax Highlighting](https://github.com/Code52/pretzel/wiki/Syntax-Highlighting), but it says

> By default Pretzel use highlight.js but any highlighter supporting the `&lt;pre&gt;&lt;code&gt;` html tag can be used (like Prism): you just have to replace the highlight.js css and js files by the chosen highlighter.

Alternatively, you can use my [Pretzel.MarkdownIt](https://github.com/thoemmi/Pretzel.MarkdownIt) plugin, which adds syntax highlighting directly to the rendered html. (shameless plug :smile:)

**Comment by laedit** [comment]
The wiki describe the behavior of the current master branch, v0.2 doesn't support all syntax.
I was planing to release the V0.3 this week-end but @thoemmi have found another bug that I prefer to fix before release it.

**Comment by JuergenGutsch** [comment]
@laedit: great news. Thanks. I thought about this :) 0.2.0.42 is the current released versions, that's why I wrote this. With this news in mind and if @gburghardt agrees, this issue can be closed.
@thoemmi: I use prism.js, but anyway, the best highlighter will not work if the the markup (HTML) doesn't work ;)

**Comment by thoemmi** [comment]
@JuergenGutsch well, if you#re interested, I could change my plugin to not generate inline styles, but rely on an external Javascript highlighter.

**Comment by JuergenGutsch** [comment]
@thoemmi Many thanks :) But from my perspective this is not really needed, if we get a new release soon.
This would be a temporary solution to get the behavior that CommonMark.NET should provide, right? So you changes are not longer needed after the release. ;)
I'll start my new blog with pretzel in the next days and personally I'm able to wait some more days or to live without a proper code highlighting a few days :)

**Comment by laedit** [comment]
Sorry, I haven't got the time to do it, but I will try to release it this week.

**Comment by gburghardt** [comment]
@laedit: No problem. Thanks for following up. I'm closing this since v0.3 fixes this.
