### ISSUE TITLE
DotLiquid version conflict between 0.3 release and Pretzel.Logic nuget package

### ISSUE THREAD

**Issue by k94ll13nn3** [Code52/pretzel#280]
After the release of the new version of Pretzel, I wanted to update my existing plugins in order to use the new NuGet package.

But I am facing some problems with the DotLiquid package: in the 0.3 zip file, the DotLiquid package is at version 1.0.0 but the Pretzel.Logic NuGet package is targeting the 1.8.0 version of DotLiquid, which causes an error when Pretzel is trying to load the plugins. 

I think it may be a side effect of #273 where a custom DotLiquid dll has been introduced (hence the 1.0.0 version).

I have changed the reference in my plugins with the custom DotLiquid package int the 0.3 zip, and it work fine for now, but it kinda kills the advantage of having a nuget package :smile:

**Comment by laedit** [comment]
Yeah, I'll have to change the reference to DotLiquid in the Pretzel.Logic package until they accept my PR...
Thanks for letting me know :smiley:

**Comment by laedit** [comment]
The version has been update on nuget.org too.
