### ISSUE TITLE
Accessing config in an ILightweightMarkupEngine implementation

### ISSUE THREAD

**Issue by thoemmi** [Code52/pretzel#285]
I have written a plugin implementing `ILightweightMarkupEngine`. I'd like to make it configurable with options set in `_config.yml`. However, I don't see a way to access the configuration.

I ask to either add the `SiteContext` (or `SiteContext.Config`) to the container so it gets injectable, or add `SiteContext` as an additional parameter to `ILightweightMarkupEngine.Convert()`

**Comment by laedit** [comment]
Good idea, I think that at least the config should be accessible by any plugin.

**Comment by thoemmi** [comment]
`ILightweightMarkupEngine` is instantiated **before** `SiteContext` is created or the configuration (`_config.yml`) is even read.

I guess the best solution is to pass `SiteContext` as an additional parameter. However, this is a **breaking change** (though there are only two plugins as far as I know, [yours](https://github.com/laedit/Pretzel.MarkdownDeep) and [mine](https://github.com/thoemmi/Pretzel.MarkdownIt) :grin:).

Anyway, if you admit I'll prepare a PR.

**Comment by laedit** [comment]
I don't want to pass the all `SiteContext` to a plugin that in my opinion doesn't need it.
But I really think that all plugins might benefit from the config file.
So two solutions:
 - read the configuration at the start and add it to the MEF catalog
 - provide a way (helper class?) to read the configuration accessible to all plugins

Either way a PR is always welcome! :smiley:
