### ISSUE TITLE
liquid include parameter 

### ISSUE THREAD

**Issue by stinett8535** [Code52/pretzel#300]
this `{% if include.modal == true %}` in include.html
this `{% include include.html modal="test" %}` in layout.
another in index.html

I do not sure what wrong with my code, passed but does not able to get the param in include.html.
I saw this documentation from jekll documentation. so assume it's bug of pretzel. 

please correct me if I am wrong.

**Comment by laedit** [comment]
Pretzel use [dotliquid](https://github.com/dotliquid/dotliquid) for liquid processing and it seems that they haven't updated since a few years...
Sadly I haven't found another lib to replace it now, but if you know one I'll be happy to do the replacement.

**Comment by stinett8535** [comment]
Thanks for reply.  Tomorrow should have a look at dotliquid then.
