### ISSUE TITLE
Suggestion: Migration to markdig

### ISSUE THREAD

**Issue by AndreyAkinshin** [Code52/pretzel#301]
Now pretzel uses CommonMark.NET as a markdown engine. There is an another cool engine: markdig.
Markdig is faster than CommonMark.NET and it supports a lot of additional features like tables (see [full list of features](https://github.com/lunet-io/markdig#features)). What do you think about migration to markdig?

Links:
https://github.com/lunet-io/markdig
https://github.com/lunet-io/markdig#features
https://www.nuget.org/packages/Markdig/

**Comment by thoemmi** [comment]
@laedit already created a plugin using Markdig, see https://github.com/laedit/Pretzel.Markdig.

**Comment by laedit** [comment]
Thanks @thoemmi :smile: 

@AndreyAkinshin thanks for the suggestion, but I prefer keeping a simple, light and fast CommonMark engine as the default one. And like @thoemmi said it is possible to create a plugin to change the engine used or use the plugin already created.
