### ISSUE TITLE
Defining defaults for layout in _config.yml

### ISSUE THREAD

**Issue by tditiecher** [Code52/pretzel#305]
When trying to convert my Jekyll website to a Pretzel website I noticed that for Pretzel I had to specify the layout in each post while Jekyll has the concept of scoped defaults in _config.yml  as described here:  https://jekyllrb.com/docs/configuration/#front-matter-defaults .

Before I'll try to add this feature to the code, is there a reason (other than time) for not having implemented this?

**Comment by laedit** [comment]
Thanks a lot for your interest in Pretzel.
Time is the only reason, the goal of Pretzel is really to have the same features than Jekyll, but we haven't the same team to work on it 😃

**Comment by tditiecher** [comment]
Ok, then I'll see what I can do.
