### ISSUE TITLE
Post Preview

### ISSUE THREAD

**Issue by morsanu** [Code52/pretzel#308]
Is there an already built way to show only the first few lines of a post in the post list? I couldn't find any properties in the models.

I saw on [this blog](http://asp.net-hacker.rocks/2016/07/06/posting-with-pretzel.html) the use of _teaser_ in the markdown file. I tried it but it's not working. Am I missing something obvious?

**Comment by thiagoabreu** [comment]
Have you tried the "post excerpts"?

https://jekyllrb.com/docs/posts/#post-excerpts

PS: I know the link is a Jekyll documentation, but Pretzel is made to be fully compatible

**Comment by morsanu** [comment]
Thank you, it worked.
