### ISSUE TITLE
Chocolatey install - Get-BinRoot deprecated

### ISSUE THREAD

**Issue by laedit** [Code52/pretzel#318]
The method `Get-BinRoot` used to install Pretzel in `c:/tools` with Chocolatey will be deprecated as soon as Chocolatey hit the v1.

We have two solutions:

1. replace it with `Get-ToolsLocation` (available since Chocolatey v0.9.10) if anyone needs Pretzel in the `c:/tools`folder
2. install Pretzel with all the others Chocolatey packages (`c:/ProgramData/chocolatey/lib` by default)

Solution 2. is my preference since Pretzel does not require to be in this particular folder and it is the recommendation of Chocolatey team.

@Code52/team-pretzel Any opinion?

**Comment by thoemmi** [comment]
I don't use chocolatey, but I would go the recommended way, solution 2.

**Comment by laedit** [comment]
Solution 2 then 😄
