### ISSUE TITLE
Pretzel 0.7.0 uses white text for output irregardless of console background

### ISSUE THREAD

**Issue by ChristianPackmann** [Code52/pretzel#321]
Pretzel 0.7.0 seems to override the console text color to white, without setting a contrasting console background color. See this image:

![pretzel_070_whitetext](https://cloud.githubusercontent.com/assets/28438611/25782238/257c9a88-3347-11e7-9717-1f5f1451309b.png)

This seems to be just cosmetic, running "pretzel taste" works, but it's still annoying if you prefer to work in a console with white background.

**Comment by laedit** [comment]
Sorry, I hadn't think of that possibility.
I will propose a contrasting theme or at least a color visible in white background.

**Comment by ChristianPackmann** [comment]
Sorry, no PR; I'm still getting used to GitHub. This change should provide readable colors regardless of console color settings.

```C#
internal static class ConsoleTrace
{
    private static Dictionary<TraceLevel, ConsoleColor> Colors = new Dictionary<TraceLevel, ConsoleColor>
         {
             { TraceLevel.Error, ConsoleColor.DarkRed },
             { TraceLevel.Warning, ConsoleColor.DarkYellow },
             { TraceLevel.Info, ConsoleColor.White },
             { TraceLevel.Debug, ConsoleColor.Gray }
         };

    private static readonly HashSet<ConsoleColor> brightConsoleColors = new HashSet<ConsoleColor>
        {
            ConsoleColor.Blue, ConsoleColor.Cyan, ConsoleColor.Gray, ConsoleColor.Green,
            ConsoleColor.Magenta, ConsoleColor.Red, ConsoleColor.White, ConsoleColor.Yellow
        };

    static ConsoleTrace()
    {
        // If console uses bright background, adjust text colors.
        if (brightConsoleColors.Contains(Console.BackgroundColor))
        {
            Colors[TraceLevel.Info] = ConsoleColor.Black;
            Colors[TraceLevel.Debug] = ConsoleColor.DarkGray;
        }
    }

// ... 

}
```

**Comment by laedit** [comment]
Thanks, I will propose a new version with this.

**Comment by laedit** [comment]
V0.7.1 with the fix have been pushed to [GitHub releases](https://github.com/Code52/pretzel/releases/tag/v0.7.1) and [Chocolatey](https://chocolatey.org/packages/pretzel/0.7.1).
