### ISSUE TITLE
Do you support Data Files?

### ISSUE THREAD

**Issue by SunaCode** [Code52/pretzel#331]
[Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)

**Comment by laedit** [comment]
Sadly not for now, but a PR is always welcome :)

**Comment by biohazard999** [comment]
@SunaCode I'm working currently on a PR for this :) cause I want to go with [static comments](https://mademistakes.com/articles/jekyll-static-comments/)

**Comment by biohazard999** [comment]
@SunaCode: what file formats are you interested in the most? For now I plan implementing `yaml` and `json`

**Comment by SunaCode** [comment]
@biohazard999: my use-case is to generate partial page content from data, therefore using data files + partial layout templates. yaml and json both are fine. even csv would do it ;)

**Comment by biohazard999** [comment]
@SunaCode you can checkout my PR and look if this works for you :)
