### ISSUE TITLE
Fix warnings in tests produced by xunit analyzer

### ISSUE THREAD

**Issue by biohazard999** [Code52/pretzel#332]
After upgrading to the latest version of xunit there are a lot of warning about the assertions.

Should we just fix those warning or should we move to a fluent assertion library like [Shouldly](https://github.com/shouldly/shouldly) to make the assertions more readable?

**Comment by laedit** [comment]
Thanks, I was having that in mind after seeing the 100+ messages in the appveyor builds :)

For the time being, let's just fix the warnings.
