### ISSUE TITLE
My Post in the dotnet advent

### ISSUE THREAD

**Issue by biohazard999** [Code52/pretzel#361]
Just for @laedit :) https://blog.delegate.at/2019/12/05/the-third-annual-csharp-advent-pretzel-journey.html

Will be published broad tomorrow

**Comment by laedit** [comment]
Yay thanks!
I will read it ASAP :)

**Comment by laedit** [comment]
Wow, thanks a lot for this beautiful article! :D
I too had a great time working/exchanging with you and I hope that we will have that occasion again.
Now that I have read the article i will close this issue :p
