### ISSUE TITLE
Discussion: Documentation/Multipart blog support

### ISSUE THREAD

**Issue by JakeGinnivan** [Code52/pretzel#62]
I want to extend the PageContext to have a DirectoryPages property, which contains the other pages in the folder.

This will enable me to create folders in my pretzel site for a category or multipart blog post. 

Here is an example of the folder:

MyMultipartBlogPost
- Part1.md
- Part2.md
- Part3.md

in my layout I will header the content with:

```
<li>
@foreach (var page in Model.DirectoryPages)
{
    <li><a href="@page.Filename">@page.Title</a></li>
}
</li>
```

So when you view part 1, 2 or 3 you will get the other posts in the directory. and when I add part4, all the pages will update automatically.

Additional features would be supporting a 'order' keyword in the front matter etc.

**Comment by markvantilburg** [comment]
What would be the syntax to use this in markdown. Maybe we could add some directory screenshot/example here. It can be me but it cannot really discover how to use this feature the right way.

**Comment by laedit** [comment]
There is an issue with the use of liquid tag in markdown in the last release, have you tried with an exec build from the source?
