### ISSUE TITLE
Update Self

### ISSUE THREAD

**Issue by JakeGinnivan** [Code52/pretzel#90]
Like NuGet, pretzel should support a 'pretzel update' command which will update in-place. 

This will enable scenario's where the exe is copied into source control with documentation etc, and want to be able to simply update to the latest version.

The feature should be updated when extension support is added, so extensions are updated as well.

**Comment by laedit** [comment]
Is this really necessary with the package available in chocolatey?

**Comment by shiftkey** [comment]
Not really
